version: '2'

services:
    nginx:
        build: ./nginx
        image: nginx:gnom
        ports:
        - "80:80"
        container_name: nginx-reverse-proxy
        volumes_from:
            - api
        links:
            - api:api
    api:
        build: ./api
        image: api:gnom
        container_name: api
        volumes:
            - "./public/dist/:/var/www/gnom-app/public/dist/"
        expose:
          - "8080"
